/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRTS;

import DTS.Consultas;
import DTS.PieChart;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
/**
 *
 * @author Cris
 */
public class Principal extends javax.swing.JFrame {
    PieChart PC = new PieChart();
    Consultas Datos = new Consultas();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        disabled();
    }

    public void disabled () {
           CBoxQD.setVisible(false);
        BtnQuery.setVisible(false);
    }
    public void enabled() {
        CBoxQD.setVisible(true);
        BtnQuery.setVisible(true);
    }
    
    public void cargarAviones() {
        DefaultComboBoxModel cobomodel = new DefaultComboBoxModel(Datos.cargarAviones());
        CBoxQD.setModel(cobomodel);
        enabled();
    }
    public void cargarAerolineas() {
        DefaultComboBoxModel cobomodel = new DefaultComboBoxModel(Datos.cargarAerolineas());
        CBoxQD.setModel(cobomodel);
        enabled();
    }
    
    
    public void buscarCVuelos() {
        String[] column = {"Modelo Avion", "Cantidad de Vuelos"};
        String selection = CBoxQD.getSelectedItem().toString();
        Object[] row = { selection,Datos.obtenerCantidadVuelos(Datos.obtenerCodigo(selection))};
        
        
        DefaultTableModel model = new DefaultTableModel(column,0);
        
        TblData.setModel(model);
        model.addRow(row);
    }
    public void buscarAL() {
        String[] column = {"Aerolinea", "Cantidad de Vuelos"};
        String selection = CBoxQD.getSelectedItem().toString();
        Object[] row = { selection,Datos.obtenerCantidadVuelosAL(selection)};
        
        
        DefaultTableModel model = new DefaultTableModel(column,0);
        
        TblData.setModel(model);
        model.addRow(row);
    }
    public void buscarTRxAL() {
        String[] column = {"Nombre", "Aerolinea", "Rol", "Id Vuelo"};
        String selection = CBoxQD.getSelectedItem().toString();
        ArrayList<String[]> rows = Datos.obtenerTripulacionAL(selection);
        
        
        DefaultTableModel model = new DefaultTableModel(column,0);
        
        TblData.setModel(model);
        for (int i = 0; i < rows.size(); i++) {
            String[] row = rows.get(i);
            model.addRow(row);
        }
        
    }
    public void buscarPilotos() {
        String[] column = {"Nombre", "Aerolinea", "Modelo Avion", "Estado Puerta"};
        ArrayList<String[]> rows = Datos.obtenerPilotos();
        
        
        DefaultTableModel model = new DefaultTableModel(column,0);
        
        TblData.setModel(model);
        for (int i = 0; i < rows.size(); i++) {
            String[] row = rows.get(i);
            model.addRow(row);
        }
        
    }
    public void buscarPistas() {
        String[] column = {"ID Vuelo", "Aeropuerto", "Pista", "Estado"};
        ArrayList<String[]> rows = Datos.obtenerPistas();
        
        
        DefaultTableModel model = new DefaultTableModel(column,0);
        
        TblData.setModel(model);
        for (int i = 0; i < rows.size(); i++) {
            String[] row = rows.get(i);
            model.addRow(row);
        }
        
    }

     public void buscarTripulantes() {


        String[] column = {"Nombre", "Edad"};
        ArrayList<String[]> rows = Datos.buscarTripulantes();
        
        
        DefaultTableModel model = new DefaultTableModel(column,0);
        

        TblData.setModel(model);


        for (int i = 0; i < rows.size(); i++) {
            String[] row = rows.get(i);
            model.addRow(row);
        }

     }

        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BtnGrCV = new javax.swing.JRadioButton();
        BtnGrA = new javax.swing.JRadioButton();
        BtnGrP = new javax.swing.JRadioButton();
        SP = new javax.swing.JScrollPane();
        TblData = new javax.swing.JTable();
        BtnSearch = new javax.swing.JButton();
        BtnQuery = new javax.swing.JButton();
        BtnGrSC = new javax.swing.JRadioButton();
        BtnGrVP = new javax.swing.JRadioButton();
        CBoxQD = new javax.swing.JComboBox<>();
        BtnGrTP = new javax.swing.JRadioButton();
        Menu = new javax.swing.JMenuBar();
        MStart = new javax.swing.JMenu();
        BtnGraph = new javax.swing.JMenuItem();
        BtnExit = new javax.swing.JMenuItem();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AeroPatos");

        buttonGroup1.add(BtnGrCV);
        BtnGrCV.setText("Cantidad de Vuelos");

        buttonGroup1.add(BtnGrA);
        BtnGrA.setSelected(true);
        BtnGrA.setText("Aerolineas");

        buttonGroup1.add(BtnGrP);
        BtnGrP.setText("Pilotos");

        TblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        SP.setViewportView(TblData);

        BtnSearch.setText("Buscar");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        BtnQuery.setText("Consultar");
        BtnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQueryActionPerformed(evt);
            }
        });

        buttonGroup1.add(BtnGrSC);
        BtnGrSC.setText("Servicio al cliente");

        buttonGroup1.add(BtnGrVP);
        BtnGrVP.setText("Vuelos desde Panama");

        buttonGroup1.add(BtnGrTP);
        BtnGrTP.setText("Tripulantes");

        MStart.setText("Inicio");

        BtnGraph.setText("Gráfico");
        BtnGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraphActionPerformed(evt);
            }
        });
        MStart.add(BtnGraph);

        BtnExit.setText("Salir");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        MStart.add(BtnExit);


        Menu.add(MStart);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SP)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnGrCV)
                            .addComponent(BtnGrA)
                            .addComponent(BtnGrVP))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnGrTP)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnGrP)
                                        .addGap(55, 55, 55))
                                    .addComponent(BtnGrSC))
                                .addGap(49, 49, 49)
                                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                                .addComponent(CBoxQD, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)

                                .addComponent(BtnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))))


                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGrCV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnGrA)
                                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnGrP))
                            .addComponent(CBoxQD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnGrSC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(BtnGrVP)
                    .addComponent(BtnGrTP))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void BtnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQueryActionPerformed
        if(BtnGrCV.isSelected()) {

            buscarCVuelos();
        } else  if (BtnGrA.isSelected()) {
            buscarAL();
        } else  if (BtnGrSC.isSelected()) {
            buscarTRxAL();
        }
        
        
    }//GEN-LAST:event_BtnQueryActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraphActionPerformed
        PC.BarChartz();
    }//GEN-LAST:event_BtnGraphActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        disabled();
        if(BtnGrCV.isSelected()) {
            cargarAviones();
        } else  if (BtnGrA.isSelected() || BtnGrSC.isSelected()) {
            cargarAerolineas();
        } else if (BtnGrP.isSelected()) {
           buscarPilotos();
        } else if (BtnGrVP.isSelected()) {
            buscarPistas();
        } else if (BtnGrTP.isSelected()) {
            buscarTripulantes();
        }
    }//GEN-LAST:event_BtnSearchActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {     
        
        try{
            UIManager.setLookAndFeel(new FlatAtomOneDarkIJTheme());
        } catch (Exception e){
            e.printStackTrace();
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatAtomOneDarkIJTheme".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnExit;
    private javax.swing.JRadioButton BtnGrA;
    private javax.swing.JRadioButton BtnGrCV;
    private javax.swing.JRadioButton BtnGrP;
    private javax.swing.JRadioButton BtnGrSC;
    private javax.swing.JRadioButton BtnGrTP;
    private javax.swing.JRadioButton BtnGrVP;
    private javax.swing.JMenuItem BtnGraph;
    private javax.swing.JButton BtnQuery;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JComboBox<String> CBoxQD;
    private javax.swing.JMenu MStart;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JScrollPane SP;
    private javax.swing.JTable TblData;
    private javax.swing.ButtonGroup buttonGroup1;

    // End of variables declaration//GEN-END:variables
}
